[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "kitty --detach --directory=$PWD" --silent'
desc = "Open kitty terminal here"
[[mgr.prepend_keymap]]
on   = "="
for  = "unix"
run  = 'shell "kitty --detach --directory=$PWD -e yazi" --silent'
desc = "Open kitty terminal here"
[[mgr.prepend_keymap]]
on   = [ "i" ]
run = "plugin easyjump"
desc = "easyjump"
[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"
[[mgr.prepend_keymap]]
on   = "~"
run  = "cd ~"
desc = "Enter the child directory, or open the file"
[[mgr.prepend_keymap]]
on   = "`"
run  = "cd ~/workspace/linuxpc/"
desc = "Enter the child directory, or open the file"
